version: '3.8'

services:
  safemed-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: safemed-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  safemed-postgres:
    image: postgres:15-alpine
    container_name: safemed-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: safemed_user
      POSTGRES_PASSWORD: safemed_password
      POSTGRES_DB: safemed_audit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: